"""add_category_to_food_items

Revision ID: 2432b04bb9cd
Revises: 77994dade025
Create Date: 2026-05-13 21:25:37.166624
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '2432b04bb9cd'
down_revision: Union[str, None] = '77994dade025'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_items', sa.Column('category', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food_items', 'category')
    # ### end Alembic commands ###
