"""add_assistant_action_logs

Revision ID: 28175e600252
Revises: 1fad27e2d83a
Create Date: 2026-05-18 19:37:16.529021
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

revision: str = '28175e600252'
down_revision: Union[str, None] = '1fad27e2d83a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assistant_action_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action_id', sa.String(length=100), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('requires_confirmation', sa.Boolean(), nullable=False),
    sa.Column('result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('before_snapshot_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_snapshot_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assistant_action_logs_action_id'), 'assistant_action_logs', ['action_id'], unique=False)
    op.create_index(op.f('ix_assistant_action_logs_action_type'), 'assistant_action_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_assistant_action_logs_user_id'), 'assistant_action_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assistant_action_logs_user_id'), table_name='assistant_action_logs')
    op.drop_index(op.f('ix_assistant_action_logs_action_type'), table_name='assistant_action_logs')
    op.drop_index(op.f('ix_assistant_action_logs_action_id'), table_name='assistant_action_logs')
    op.drop_table('assistant_action_logs')
    # ### end Alembic commands ###
