"""add_nutrition_goals_to_users

Revision ID: 6fd986e8ac34
Revises: b77fa111317f
Create Date: 2026-05-14 10:40:00.770447
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '6fd986e8ac34'
down_revision: Union[str, None] = 'b77fa111317f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('target_calories', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('target_protein', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('target_carbs', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('target_fat', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('goal_type', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'goal_type')
    op.drop_column('users', 'target_fat')
    op.drop_column('users', 'target_carbs')
    op.drop_column('users', 'target_protein')
    op.drop_column('users', 'target_calories')
    # ### end Alembic commands ###
