"""add_ai_logs_table

Revision ID: 77994dade025
Revises: e11e51ca5a14
Create Date: 2026-05-13 20:58:39.210278
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '77994dade025'
down_revision: Union[str, None] = 'e11e51ca5a14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('engine', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('prompt_preview', sa.Text(), nullable=True),
    sa.Column('response_preview', sa.Text(), nullable=True),
    sa.Column('latency', sa.String(length=20), nullable=True),
    sa.Column('token_usage', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('cache_hit', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_logs_user_id'), 'ai_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_logs_user_id'), table_name='ai_logs')
    op.drop_table('ai_logs')
    # ### end Alembic commands ###
