"""add_confidence_source_estimated_to_food_items

Revision ID: b77fa111317f
Revises: 2432b04bb9cd
Create Date: 2026-05-13 21:57:05.665119
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'b77fa111317f'
down_revision: Union[str, None] = '2432b04bb9cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 先添加为 nullable，填充默认值后再设 NOT NULL
    op.add_column('food_items', sa.Column('confidence', sa.Float(), nullable=True))
    op.add_column('food_items', sa.Column('source', sa.String(length=20), nullable=True))
    op.add_column('food_items', sa.Column('estimated', sa.Boolean(), nullable=True))

    # 为历史数据填充默认值
    op.execute("UPDATE food_items SET confidence = 0.0 WHERE confidence IS NULL")
    op.execute("UPDATE food_items SET source = 'ocr' WHERE source IS NULL")
    op.execute("UPDATE food_items SET estimated = false WHERE estimated IS NULL")

    # 设为 NOT NULL
    op.alter_column('food_items', 'confidence', nullable=False)
    op.alter_column('food_items', 'source', nullable=False)
    op.alter_column('food_items', 'estimated', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food_items', 'estimated')
    op.drop_column('food_items', 'source')
    op.drop_column('food_items', 'confidence')
    # ### end Alembic commands ###
