"""add_phone_to_users

Revision ID: ebeecdbc1a11
Revises: fbdd0ac49e6d
Create Date: 2026-05-11 23:48:57.584187
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'ebeecdbc1a11'
down_revision: Union[str, None] = 'fbdd0ac49e6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=False))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
