"""add core tables

Revision ID: fbdd0ac49e6d
Revises: dff04cbdb72d
Create Date: 2026-05-11 23:32:50.149236
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'fbdd0ac49e6d'
down_revision: Union[str, None] = 'dff04cbdb72d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'analyze_tasks', 'food_records', ['record_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'analyze_tasks', type_='foreignkey')
    # ### end Alembic commands ###
